### ISSUE TITLE
ValueError: cannot reindex from a duplicate axis

### ISSUE THREAD

**Issue by DUAN-GAO** [theislab/single-cell-tutorial#82]
Hi,when I execute this code :
adata = adata.concatenate(adata_tmp, batch_key='sample_id')
I got below error,
ValueError: cannot reindex from a duplicate axis

could u help, many thanks

**Comment by LuckyMD** [comment]
Hey! Are you getting this error with the tutorial data or your own data? It looks like you might have a barcode that is both in `adata.obs_names` and `adata_tmp.obs_names`. Or otherwise, check your `adata.var` and `adata_tmp.var` for columns with the same name.

**Comment by DUAN-GAO** [comment]
Mr Malte, I used the sample dataset GEO set GSE92332_RAW, but soon after second GEO data read, when it tried to combine with the first GEO data, it told me cannot reindex from a duplicate axis

**Comment by onsamoylova** [comment]
Any updates? Did you managed this problem? (Same here, with tutorial dataset)

**Comment by onsamoylova** [comment]
after line:
        adata.var = genes
Add: 
       adata.var_names_make_unique()

**Comment by LuckyMD** [comment]
Thanks for the solution. I believe it's reported in another issue as well. It is fixed in the latest version which is only available in PR #58 though.

**Comment by Lavieenrose123** [comment]
> Thanks for the solution. I believe it's reported in another issue as well. It is fixed in the latest version which is only available in PR #58 though.

Hi, I performed the code from your latest notebook (1906) but I still encountered the same problem. I found the problem is due to non-unique index of `adata.var`. Maybe the reason is, I guess, you didn't make the `gene_symbol`, i.e., the index of `adata.var,` to be unique for the first mouse cell (code in jupyter cell #5). It seems that you should also add `adata.var_names_make_unique()` there. 

BTW, cound you please tell me why the same gene_symbol shared different gene_id in that dataset? Thanks!

**Comment by LuckyMD** [comment]
Hi @Lavieenrose123,

This is exactly the fixthat is in PR #58 as mentioned.

> BTW, cound you please tell me why the same gene_symbol shared different gene_id in that dataset? Thanks!

I think this occurs as when you map reads to the transcriptome during alignment, you might be aligning to two different transcripts that map to the same gene (e.g., isoforms).
